{% set version = "3.0.0" %}

package:
  name: graphviz
  version: {{ version }}

source:
  - url: https://gitlab.com/graphviz/graphviz/-/archive/3.0.0/graphviz-3.0.0.tar.gz
    #  - url: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/3.0.0/graphviz-3.0.0.tar.gz
    sha256: 59931082a3638139e06c296b96e860a9d338432af06f7f57a6ad8da5cbf465c7
    patches:
      - patches/getopt_windows_build_fix.patch
      # - patches/0001-Rename-vpsc-block.h-vpsc-v_block.h.patch
      # - patches/0002-Add-CMake-option-INSTALL_DEPENDENCY_DLLS-default-off.patch # [win]
      # - patches/0003-Specify-dependency-on-expat-for-lib-common.patch
      # - patches/0004-Always-link-to-getopt-on-Windows.patch # [win]
      # - patches/0005-Remove-requirement-of-hard-coded-DLLs-in-PATH.patch # [win]
      # - patches/0006-Add-support-for-GTS-in-CMake-builds.patch
      # - patches/0007-Fix-logic-for-finding-harfbuzz.patch
    # Prefer header only compat layer, even though m2-libtool might work
  - url: https://gitlab.com/graphviz/graphviz-windows-dependencies/-/raw/c7eafb3c/x64/include/ltdl.h
    sha256: a3cf376bca2965634ba05926d4065a46331e71c487d84a4c6aceb795e9458bfd
    folder: ltdl_compat

build:
  number: 0
  detect_binary_files_with_prefix: true  # [unix]
  missing_dso_whitelist:
    - "*neato*so*"
    - "$RPATH/libm.so*"
    - "$RPATH/libc.so*"
    - "$RPATH/libdl.so*"
    - "$RPATH/ld-linux*.so*"
    - "$RPATH/libpthread.so*"
    - "$RPATH/librt.so*"
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config                                          # [unix]
    - make                                                # [unix]
    - bison                                               # [unix]
    - libtool                                             # [unix]
    - automake                                            # [unix]
    - autoconf                                            # [unix]
    - cmake
    - ninja
    - python
    - m2-gawk                                             # [win]
    - m2-flex                                             # [win]
    - m2-bison                                            # [win]
    - m2-gzip # [win]
    - perl                                                # [win]
    - patch                                               # [linux]
    - m2-patch                                            # [win]
    - git
    - libxcb                                              # [linux]
    - {{ cdt('libxrender')  }}                            # [linux]
    - {{ cdt('libxrender-devel')  }}                      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}                   # [linux]
    - {{ cdt('libx11-devel') }}                           # [linux]
    - {{ cdt('libxext') }}                                # [linux]
    - {{ cdt('libxext-devel') }}                          # [linux]
    - {{ cdt('libxau-devel') }}                           # [linux]
    - {{ cdt('libxau') }}                                 # [linux]

  host:
    # --with-expat=yes
    - expat
    # --with-freetype2
    - freetype
    # --with-fontconfig=yes
    # --with-gts=yes
    - gts
    # --with-gdk-pixbuf=yes
    - gdk-pixbuf                                          # [unix]
    - glib
    # --enable-ltdl
    - libtool                                             # [unix]
    # --with-webp=yes
    - libwebp-base                                        # [unix]
    # --with-pangocairo=yes
    - pango #[not win]
    - cairo
    # default requirement
    - zlib                                                # [unix]
    - libtiff
    - libpng
    # --with-libgd=yes
    - libgd >2.2 # [not win]
    - libxcb                                              # [linux]
    - librsvg #[linux]
    - devil
    - getopt-win32

test:
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: https://graphviz.gitlab.io/documentation/
  dev_url: https://gitlab.com/graphviz/graphviz/

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - johanneskoester
    - nehaljwani
