package:
  name: graphviz
  version: "2.40.1"  # [unix]
  version: "2.38"    # [win]

source:
  fn:  graphviz.tar.gz  # [unix]
  url: https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz  # [unix]
  md5: 4ea6fd64603536406166600bcc296fc8  # [unix]

  fn:  graphviz-2.38.zip  # [win]
  url: https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.zip  # [win]
  md5: d028f49e047e2a25fdb7c0aa323a3945  # [win]

  patches:
    -  darwin.patch  # [osx]


build:
  number: 0
  detect_binary_files_with_prefix: True  # [unix]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - autoconf
    - automake
    - pkg-config                         # [osx]
    - libtool                            # [unix]

  host:
    - expat                              # [unix]
    - cairo                              # [unix]
    - freetype                           # [unix]
    - jpeg                               # [unix]
    - libpng                             # [unix]
    - libtiff                            # [unix]
    - pango                              # [unix]
    - zlib                               # [unix]

  run:
    - libtool                            # [linux]
    - expat                              # [unix]
    - cairo                              # [unix]
    - freetype                           # [unix]
    - jpeg                               # [unix]
    - libpng                             # [unix]
    - libtiff                            # [unix]
    - pango                              # [unix]
    - zlib                               # [unix]


test:
  commands:
    - dot -V
    - neato -?  # [unix]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
  files:
    - sample.dot


about:
  home: https://www.graphviz.org/
  license: EPL v1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: https://graphviz.gitlab.io/documentation/
  dev_url: https://gitlab.com/graphviz/graphviz/


extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
