{% set version = "2.40.1" %}
{% set win_version = version[:-2] %}

package:
  name: graphviz
  version: {{ version }}

source:
  fn:  graphviz-{{ version }}.tar.gz  # [unix]
  url: https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
  md5: 4ea6fd64603536406166600bcc296fc8  # [unix]

  fn:  graphviz-{{ win_version }}.zip  # [win]
  url: http://www.graphviz.org/pub/graphviz/stable/windows/graphviz-{{ win_version }}.zip  # [win]
  md5: d028f49e047e2a25fdb7c0aa323a3945  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: True  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    # - libtool     # [unix]
    # - autoconf
    # - automake
    - pkg-config  # [unix]
  host:
    - cairo       # [unix]
    - expat       # [unix]
    - libpng      # [unix]
    - libtiff     # [unix]
    - freetype    # [unix]
    - jpeg        # [unix]
    - pango       # [unix]
    - zlib        # [unix]

test:
  commands:
    - dot -V
    - neato -?  # [unix]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  license: EPL v1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: http://www.graphviz.org/Documentation.php
  dev_url: https://github.com/ellson/graphviz

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - mingwandroid
