{% set version = "12.2.1" %}

package:
  name: graphviz
  version: {{ version }}

source:
  - url: https://gitlab.com/graphviz/graphviz/-/archive/{{ version }}/graphviz-{{ version }}.tar.gz
    sha256: 91d444b4dabdaf5bfa7c6fcc3a1ee5d41e588af6079ebc030f0acb79e48a56ea
    patches:
      - patches/0001-Always-link-to-getopt-on-Windows.patch
      - patches/0002-Remove-requirement-of-hard-coded-DLLs-in-PATH.patch
      - patches/0003-Use-WebP-CMake-targets-instead-of-PkgConfig.patch
      - patches/0004-Fix-dependencies-for-gvplugin_gd.patch
      - patches/0005-Don-t-rely-on-pkgconfig-for-GTS-on-Windows.patch
  # Prefer header only compat layer, even though m2-libtool might work
  - url: https://gitlab.com/graphviz/graphviz-windows-dependencies/-/raw/c7eafb3c/x64/include/ltdl.h
    sha256: a3cf376bca2965634ba05926d4065a46331e71c487d84a4c6aceb795e9458bfd
    folder: ltdl_compat

build:
  # gtk3 not available for s390x
  skip: true  # [s390x]
  number: 3
  # gkd-pixbuf -> libtiff -> liblzma (not a direct dep)
  ignore_run_exports:  # [unix]
    - liblzma  # [unix]
  detect_binary_files_with_prefix: true  # [unix]
  missing_dso_whitelist:  # [linux]
    - "**/libc.so.6"  # [linux]
    - "**/libpthread.so.0"  # [linux]
    - "**/libdl.so.2"  # [linux]
    - "**/librt.so.1"  # [linux]
    - "**/libm.so.6"  # [linux]
    - "**/ld-linux-x86-64.so.2"  # [linux]
    - "**/ld64.so.1"  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]
    - bison  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
    - m4  # [unix]
    - cmake  # [win]
    - ninja-base  # [win]
    - python 3.9
    - m2-gawk  # [win]
    - m2-flex  # [win]
    - m2-bison  # [win]
    - perl 5.*  # [win]
    - gawk  # [not win]
    - sed  # [not win]
    - patch  # [not win]
    - m2-patch  # [win]
    - pthread-stubs  # [linux]
    # TODO: map CDT mesa-libegl to new X11 package
    # - { cdt('mesa-libegl') }
    # TODO: map CDT mesa-libgbm to new X11 package
    # - { cdt('mesa-libgbm') }
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT alsa-lib-devel to new X11 package
    # - { cdt('alsa-lib-devel') }
    # TODO: map CDT gtkmm24-devel to new X11 package
    # - { cdt('gtkmm24-devel') }
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT pciutils-devel to new X11 package
    # - { cdt('pciutils-devel') }
    # TODO: map CDT libselinux to new X11 package
    # - { cdt('libselinux') }
    # TODO: map CDT libselinux-devel to new X11 package
    # - { cdt('libselinux-devel') }
    # TODO: map CDT expat-devel to new X11 package
    # - { cdt('expat-devel') }
    # TODO: map CDT pcre to new X11 package
    # - { cdt('pcre') }
    # TODO: map CDT libxkbcommon-devel to new X11 package
    # - { cdt('libxkbcommon-devel') }
    # TODO: map CDT cups-devel to new X11 package
    # - { cdt('cups-devel') }
    # TODO: map CDT libcom_err to new X11 package
    # - { cdt('libcom_err') }
    # TODO: map CDT gnutls to new X11 package
    # - { cdt('gnutls') }
    # TODO: map CDT avahi-libs to new X11 package
    # - { cdt('avahi-libs') }
    # TODO: map CDT libgpg-error to new X11 package
    # - { cdt('libgpg-error') }
    # TODO: map CDT libtasn1 to new X11 package
    # - { cdt('libtasn1') }
  host:
    # --with-poppler=yes
    - poppler 24.09
    # --with-expat=yes
    - expat
    # --with-freetype2
    - freetype 2.12.1
    # --with-fontconfig=yes
    - fontconfig
    # --with-gts=yes
    - gts
    # --with-gdk-pixbuf=yes
    - gdk-pixbuf  # [unix]
    # --with-libgd=yes
    - libgd
    # --with-gdk=yes
    - gtk3  # [linux]
    # --with-rsvg=yes
    - librsvg  # [unix]
    # --enable-ltdl
    - libtool  # [unix]
    # --with-webp=yes
    - libwebp 1.2.4
    - libwebp-base
    # --with-pangocairo=yes
    - cairo
    - pango
    - libglib
    # default requirement
    - zlib
    - getopt-win32  # [win]
    - xorg-xproto
    - xorg-libx11
    - xorg-libxext
    - xorg-libxext
    - xorg-libxrender
    - libgl-devel
    - mesa-dri-drivers
    - xorg-libxau
    - xorg-libxcomposite
    - xorg-libxcursor
    - xorg-libxi
    - xorg-libxrandr
    - xorg-libxscrnsaver
    - xorg-libxtst
    - xorg-libxdamage
    - xorg-libxdamage
    - xorg-libxfixes
    - xorg-libxfixes
    - xorg-libxxf86vm
    - xorg-libxxf86vm
    - xorg-libsm
    - xorg-libice
    - libxcb
    - libxcb
    - libglx
    - libegl
    - xcb-util
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xorg-libxinerama
    - xorg-libxau
    - xorg-xproto
    - xorg-libxrender
    - xorg-libx11
    - xorg-libxext
  run:
    - expat
    - gts
    - libgd
    - gtk3  # [linux]
    - librsvg  # [unix]
    - libtool  # [unix]
    - libwebp
    - libwebp-base
    - cairo
    - pango
    - libglib
    - zlib
    - getopt-win32  # [win]
    - fonts-conda-ecosystem
    # Not linked in directly, likely interface deps? add 'em anyway!
    - gdk-pixbuf  # [unix]
    - fontconfig
    - freetype
    - {{ pin_compatible('poppler', max_pin='x.x.x') }}

test:
  files:
    - sample.dot

about:
  home: https://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: https://graphviz.gitlab.io/documentation/
  dev_url: https://gitlab.com/graphviz/graphviz/

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - johanneskoester
    - nehaljwani