travis:
  secure:
    BINSTAR_TOKEN: jrTYL3FGebY5bmE5WoIrCYI9H1SycVKBK34qw8DaqJ2jpFM6ZMkonyhxpt6hgi8ZShFnAnksXXEsSuVDhYEixRAQDLW5EI2bJ/+wsC6c4XDmGl5ykiMJF7Rnm3qC4nTOhDhzxNFD+3i/vKGjut19yRLwmO+M3ciHJ/8i0jVvPTq4foHwT6auY0i0L2ZaOEHdTSptZ2Kt3oClK7M5q8oXWhHMv8BYxQSv0Ao4d/sh2pmc7ngmpPQFY3jUSbqjV4uDr9u0nE2bn1KjWCFEZLhLSQMYzdAPhx7DYaC+HAwWRHgdceuImajBsF9WTfWJqLE7GctnPCYavgzC8JiBi7QZoEKCZ0eX9KYiC8XbfKlscWr+cXP98IIYcuPF467qmfpcYrKZ6gNrCGax/terbnNXp+pMHJtKI84bkULXYy3TiFliBw8BuO0ehSBrSDvx8Z4Rmvc7cbE0vrmh48kSksvysl3xcuWkvUFDIINjf2evJnUpGIXNWbOkrB5myXnEl8HN6ARlO2/C6ixx2ulwuC8IVxE4zSXRtca2gcZeXspoak3ze8IVW/1K9gzaUfA+wSrRFbxe88I5stFajbRaQL5gdUyxL+RsOLHE+mg9ZOuuHRxXpN0U3H5Popff6EDEJhtB/orhSG0HcfFYn/4ghSc1opMguvvnTgh4VZt3HUacgaU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
