travis:
  secure:
    BINSTAR_TOKEN: nEzvtCbh+pjdTPMwjtWUuwFTeYU/JRchPbZx/KgsYvVRVS6IQtSL3+5+9F2ZNC0gfNSdQFUSLj1oeSVfFwkkDD8LGPp1SJta2hC2jpxA7ogy6PT6yQ4MJ+CIF274O5l3IeLjxt1N4csrGGXUxFvJQ+5ZIowGWzAWQ7Khf/dcCOItoZLPR+LwsE6WuW8hwzCTP7Y7AlAYZk+sTu9B5N0fLAaAegZSlp2A26iLq2O5hTrMK02n8R4U7YAoJ2tM2NC9P9/LZrObqOjA/hc0K4odoYVltYR4YPKSWB5ls0/OmQEcnrIWLivxb/nKS7jVgDX7DbUQmF5vLBrKvz3SWJ2ERvKoDD5v+4buAR69v4BoeZ6vtl5jpkCvKc+fV2gVxBV/LgEC3tL/tgUrNaKCzeR1tJ979oqMO5WPw+gTFaqMeTyvCdjJjSsayjgivbbpoy7FL9HjAVNYbgljjFBTf3LTjZt/Z+A3g7Qq8SycqOHQhGcdZRHNh9e3JFXXxs32XIgMeJPf0C3YeZrzj+BtlE96YGCiqt7W9iPTrS14f16ezDyXxHkZeZMG4lVIgDiIwCc4MdKcwsQTVN94Pvuyrj74WAtOSqLYEeTQY1BcUFSW0D7JM4f5xAm5MWhnCUWAAkk+keAS45gpSQffVJf0bParBtEHtkpDZepCHJI+IID8vGY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
